apiVersion: v1
kind: Namespace
metadata:
  name: three-tier-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
############################
# 3‑tier application
############################

# Backend DB config
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: three-tier-app
type: Opaque
stringData:
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: apppassword
  POSTGRES_DB: appdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: three-tier-app
data:
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
---
# DB (Postgres)
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: three-tier-app
  labels:
    app: three-tier
    tier: db
spec:
  selector:
    app: three-tier
    tier: db
  ports:
  - name: db
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: three-tier-app
  labels:
    app: three-tier
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: three-tier
      tier: db
  template:
    metadata:
      labels:
        app: three-tier
        tier: db
    spec:
      containers:
      - name: db
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
          name: db
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
---
# Backend (sample API)
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: three-tier
    tier: backend
spec:
  selector:
    app: three-tier
    tier: backend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier-app
  labels:
    app: three-tier
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier
      tier: backend
  template:
    metadata:
      labels:
        app: three-tier
        tier: backend
    spec:
      containers:
      - name: backend
        image: jkaninda/simple-api:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        # This sample API does not really use Postgres;
        # these envs are here to keep the 3‑tier pattern.
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DATABASE_PORT
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
---
# Frontend (simple NGINX page calling backend)
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-index
  namespace: three-tier-app
data:
  index.html: |
    <html>
    <head><title>3‑Tier Demo</title></head>
    <body>
      <h1>3‑Tier Demo Frontend</h1>
      <p>Backend health (raw): <a href="/api/hello">/api/hello</a></p>
      <script>
        fetch('/api/hello')
          .then(r => r.text())
          .then(t => {
            const p = document.createElement('p');
            p.innerText = 'Backend says: ' + t;
            document.body.appendChild(p);
          })
          .catch(e => console.error(e));
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: three-tier-app
  labels:
    app: three-tier
    tier: frontend
spec:
  selector:
    app: three-tier
    tier: frontend
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier-app
  labels:
    app: three-tier
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: three-tier
      tier: frontend
  template:
    metadata:
      labels:
        app: three-tier
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: nginx:alpine
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: html
        configMap:
          name: frontend-index
          items:
          - key: index.html
            path: index.html
      - name: nginx-conf
        configMap:
          name: frontend-nginx-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: three-tier-app
data:
  default.conf: |
    server {
      listen 80;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
      }
      location /api/ {
        proxy_pass http://backend.three-tier-app.svc.cluster.local:8080/;
      }
    }

---
############################
# Prometheus
############################
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes-services'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names: ['three-tier-app']
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        regex: three-tier
        action: keep
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
spec:
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observability
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.54.0
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - containerPort: 9090
          name: http
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config

---
############################
# Grafana + simple dashboard
############################
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: observability
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.observability.svc.cluster.local:9090
      isDefault: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: observability
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: three-tier-grafana-dashboard
  namespace: observability
data:
  three-tier-dashboard.json: |
    {
      "id": null,
      "uid": "three-tier-app",
      "title": "Three Tier App Overview",
      "schemaVersion": 36,
      "version": 1,
      "panels": [],
      "time": { "from": "now-1h", "to": "now" },
      "timezone": "browser"
    }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: observability
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: observability
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.1.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Viewer"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboards-json
          mountPath: /var/lib/grafana/dashboards
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasource
      - name: dashboards
        configMap:
          name: grafana-dashboards-config
      - name: dashboards-json
        configMap:
          name: three-tier-grafana-dashboard
