apiVersion: v1
kind: Service
metadata:
  name: sql01
spec:
  clusterIP: 10.43.65.117
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    name: mysql
  sessionAffinity: None
  type: ClusterIP