apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
spec:
  clusterIP: 10.43.205.182
  ports:
    - nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    name: webapp-pod
  sessionAffinity: None
  type: NodePort