apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manage-nodes-global
subjects:
  - kind: User
    name: michelle # Name is case sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: nodes-cluster-role
  apiGroup: rbac.authorization.k8s.io